### ISSUE TITLE
Using --shuffle causes Error

### ISSUE THREAD

**Issue by elicik** [elicik/slippi-helper-js#1]
Fortunately no one is using this feature, but I don't know the proper way to fix it:

> RangeError: Maximum call stack size exceeded
    at Object.<anonymous> (C:\snapshot\Slippi\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:768:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at Function.Module._load (internal/modules/cjs/loader.js:553:12)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at internal/main/run_main_module.js:17:11

**Comment by elicik** [comment]
This seems to be caused by using pkg with node v12 (https://github.com/zeit/pkg/issues/681).

Until a fix is released the solution will be to compile with node v10
